### PR TITLE
Upgrade: switch to native Promise (fixes #32)

### LINKED ISSUE #32: bluebird should be a dependency, not a peerDependency
Looking at [link](https://docs.npmjs.com/files/package.json#peerdependencies), it seems you really ought to express *bluebird* as a dependency of *liquid-node* rather than a peerDependency. If you're trying to spare people from requiring a project-wide dependency multiple times, you can recommend they use [dedupe](https://docs.npmjs.com/cli/dedupe). Using peerDependencies like this can [cause problems](https://github.com/npm/npm/issues/5080)

### PR DESCRIPTION
**Pull request by dotnil**
native-or-bluebird as dependency instead of bluebird as peerDependency

Comparing to bluebird, native `Promise` hasn't got methods like `Promise.try`, `Promise.reduce`. There was `Promise.cast` in bluebird but it's deprecated and removed for while now. Here's the equivalents:

```js
// Promise.cast(value)
Promise.resolve(value)

// Promise.try(fn)
Promise.resolve().then(fn)

// Promise.reduce(collection, reducer, initialValue)
Promise.all(collection).then(results) {
  return results.reduce(function(promise, item, index, length) {
    return promise.then(function(value) {
      return reducer(value, item, index, length)
    })
  }, initialValue)
})
```

### CODE REVIEW

**Comment by sirlantis** [comment]
:100: Looks very good, awesome!

P.S. Didn't know that library. Thanks for the tip!

**Comment by sirlantis** [comment]
A few more methods were undefined for native Promises. Travis didn't pick them up, because `bluebird` was always installed and used (since it was listed in `devDependencies`).

I fixed the issues, removed `bluebird` from `devDependencies` and and pimped TravisCI config matrix. Looks good now. :)

**Comment by dotnil** [comment]
:+1: nice. What did I miss?

**Comment by dotnil** [comment]
Found them in the [commit log](https://github.com/sirlantis/liquid-node/commits/master). Sorry for my carelessness :flushed:

**Pull request merged**
